# Local development relay configuration.
listeners:
  - name: main
    udp:
      socket:
        address: "::"
        port: 9668
    tls:
      insecure: true
    endpoint: "/moq-relay"

services:
  default:
    match:
      - authority: {any: true}
        path: {prefix: "/"}
    cache:
      enabled: true
      max_tracks: 100
      max_groups_per_track: 3

admin:
  address: "::1"
  port: 9669
  plaintext: true
