FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        libboost-context1.83.0 \
        libsodium23 \
        libgoogle-glog0v6 \
        libdouble-conversion3 \
        libgflags2.2 \
        libevent-2.1-7t64 \
        libssl3t64 \
        libzstd1 \
        libunwind8 \
        liblzma5 \
        libstdc++6 \
        ca-certificates \
        iputils-ping iproute2 ethtool \
    && rm -rf /var/lib/apt/lists/*

COPY .scratch/moxygen-install/bin/moqtextclient /usr/local/bin/moqtextclient

ENTRYPOINT ["/usr/local/bin/moqtextclient"]
